### ISSUE TITLE
Bot killing thing

### ISSUE THREAD

**Issue by nerrage** [lucas-r-cooper/Coreuptedbot#21]
```
[[u'fyresg', u'hdllo']]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "bot.py", line 423, in process_chat
    givechatbonus(s, username)
  File "bot.py", line 61, in givechatbonus
    if core_functions.hasfirstbonus(username):
  File "/root/git/Coreuptedbot/core_functions.py", line 141, in hasfirstbonus
    if user_exists(irc_user, 'chatted_today') == 0: #not on table
  File "/root/git/Coreuptedbot/core_functions.py", line 39, in user_exists
    conn_cursor.execute("SELECT COUNT(*) FROM "+table+" WHERE username = ?", t)
ProgrammingError: Recursive use of cursors not allowed.
```

RIP

**Comment by nerrage** [comment]
:thallluminati!thallluminati@thallluminati.tmi.twitch.tv 
PRIVMSG #coreupted :DarkMode                             
                                                         
[[u'thallluminati', u'DarkMode']]                        
Exception in thread Thread-3:                            
Traceback (most recent call last):                       
  File "/usr/lib/python2.7/threading.py", line 801, in __
bootstrap_inner                                          
    self.run()                                           
  File "/usr/lib/python2.7/threading.py", line 754, in ru
n                                                        
    self.__target(*self.__args, **self.__kwargs)         
  File "bot.py", line 423, in process_chat               
    givechatbonus(s, username)                           
  File "bot.py", line 61, in givechatbonus               
    if core_functions.hasfirstbonus(username):           
  File "/root/git/Coreuptedbot/core_functions.py", line 1
41, in hasfirstbonus                                     
    if user_exists(irc_user, 'chatted_today') == 0: #not 
on table                                                 
  File "/root/git/Coreuptedbot/core_functions.py", line 3
9, in user_exists                                        
    conn_cursor.execute("SELECT COUNT(*) FROM "+table+" W
HERE username = ?", t)                                   
ProgrammingError: Recursive use of cursors not allowed.  
                                                         
making announcement!

**Comment by nerrage** [comment]
With some more context from before...
```
[[u'angelskyd', u'adults drink it. no worries @Coreupted you will get there some da
y']]
:thallluminati!thallluminati@thallluminati.tmi.twitch.tv PRIVMSG #coreupted :tipS

[[u'thallluminati', u'tipS']]
:thallluminati!thallluminati@thallluminati.tmi.twitch.tv PRIVMSG #coreupted :Rigged
 Rogue tipS

[[u'thallluminati', u'Rigged Rogue tipS']]
:angelskyd!angelskyd@angelskyd.tmi.twitch.tv PRIVMSG #coreupted :@WheresTheNewBKC i
 didnt understand what you meant. i dont speak meme

[[u'angelskyd', u'@WheresTheNewBKC i didnt understand what you meant. i dont speak
meme']]
:wheresthenewbkc!wheresthenewbkc@wheresthenewbkc.tmi.twitch.tv PRIVMSG #coreupted :
@angelskyd LeL can be used for any situation

[[u'wheresthenewbkc', u'@angelskyd LeL can be used for any situation']]
PING :tmi.twitch.tv

[[u'PING', u'PING :tmi.twitch.tv']]
Pong sent
:thallluminati!thallluminati@thallluminati.tmi.twitch.tv PRIVMSG #coreupted :REEEEE
EEEEEEEE

[[u'thallluminati', u'REEEEEEEEEEEEE']]
Exception in thread Thread-3:
Traceback (most recent call last):
```

**Comment by nerrage** [comment]
Still running into this with the new bot code, sad. I'm going to close this and re-open as a new issue.
