### ISSUE TITLE
Threads fighting with sqlite

### ISSUE THREAD

**Issue by nerrage** [lucas-r-cooper/Coreuptedbot#25]
Welp, shouldn't have done a hack with ```check_same_thread=False```

```Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/lcooper/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/lcooper/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Volumes/Case Sensitive/git/Coreuptedbot/coreuptedbot/bot_main.py", line 19, in processchat
    process_chat_worker.processchat()
  File "/Volumes/Case Sensitive/git/Coreuptedbot/coreuptedbot/chat_worker.py", line 24, in processchat
    if chatter.give_first_chat_bonus():
  File "/Volumes/Case Sensitive/git/Coreuptedbot/coreuptedbot/user.py", line 71, in give_first_chat_bonus
    if self.user_exists_in_table('chatted_today'): #no soup for you
  File "/Volumes/Case Sensitive/git/Coreuptedbot/coreuptedbot/user.py", line 25, in user_exists_in_table
    self.conn_cursor.execute("SELECT COUNT(*) FROM "+tablename+" WHERE username = ?", t)
ProgrammingError: Recursive use of cursors not allowed.
```

What I think is most likely happening is that one thread creates a user object, then another thread latches onto it and is using the cursor from elsewhere. Gonna have to test with some breakpoints and such.

Ultimately I need to remove check_same_thread = False I think.

**Comment by nerrage** [comment]
After a lot of searching and fighting with debuggers, I think it will be best to move workers to separate processes, though that comes with its own difficulties

**Comment by nerrage** [comment]
Likely just need some locking mutex or something similar within ```bot_main.py`` to stop resources from fighting heh.
